#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/tama-common

PRODUCT_COPY_FILES += \
    vendor/sony/tama-common/proprietary/system/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/audiosphere.xml \
    vendor/sony/tama-common/proprietary/system/etc/permissions/privapp-permissions-com.qualcomm.location.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/sony/tama-common/proprietary/system/etc/permissions/privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-qti.xml \
    vendor/sony/tama-common/proprietary/system/etc/permissions/privapp-permissions-sony.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-sony.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/sony/tama-common/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/sony/tama-common/proprietary/system_ext/etc/init/wfdservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/wfdservice.rc \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephonyservice.xml \
    vendor/sony/tama-common/proprietary/system_ext/etc/seccomp_policy/wfdservice.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/wfdservice.policy \
    vendor/sony/tama-common/proprietary/system_ext/etc/wfdconfigsink.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/wfdconfigsink.xml \
    vendor/sony/tama-common/proprietary/vendor/camera/version.dat:$(TARGET_COPY_OUT_VENDOR)/camera/version.dat \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Codec_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Codec_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/Sony_tama_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_tama_Bluetooth_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/Sony_tama_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_tama_Codec_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/Sony_tama_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_tama_General_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/Sony_tama_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_tama_Global_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/Sony_tama_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_tama_Hdmi_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/Sony_tama_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_tama_Headset_cal.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/sony/tama-common/proprietary/vendor/etc/acdbdata/workspaceFile_Sony_tama.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/workspaceFile_Sony_tama.qwsp \
    vendor/sony/tama-common/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/sony/tama-common/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/sony/tama-common/proprietary/vendor/etc/camera/flashled_calc_parameters.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/flashled_calc_parameters.cfg \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile1.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile15.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile16.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile17.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile18.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile19.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile2.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile20.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile21.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile3.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile32.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile4.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile5.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile6.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_ORN/OEM_ORN_profile7.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile1.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile15.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile16.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile17.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile18.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile19.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile2.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile20.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile21.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile3.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile32.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile4.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile5.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile6.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PeleIL/OEM_PeleIL_profile7.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile1.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile15.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile16.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile17.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile18.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile19.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile2.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile20.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile21.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile3.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile32.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile4.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile5.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile6.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/OEM_PlayPL/OEM_PlayPL_profile7.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b00 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b01 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b02 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b03 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b04 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b05 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b06 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.b07:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.b07 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tzsuntory.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tzsuntory.mdt \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b00 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b01 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.b02:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b02 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.b03:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b03 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.b04:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b04 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.b05:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b05 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.b06:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b06 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.b07:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.b07 \
    vendor/sony/tama-common/proprietary/vendor/etc/firmware/tztpm.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/tztpm.mdt \
    vendor/sony/tama-common/proprietary/vendor/etc/idd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/idd.conf \
    vendor/sony/tama-common/proprietary/vendor/etc/iddd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/iddd.conf \
    vendor/sony/tama-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.widevine.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/android.hardware.gnss@2.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.0-service-qti.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.2-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.2-service-qti.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/android.hardware.sensors@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@2.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/init.sony-modem-switcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sony-modem-switcher.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.semc.system.idd@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.semc.system.idd@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.somc.hardware.miscta@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.somc.hardware.miscta@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vendor.somc.hardware.modemswitcher@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.somc.hardware.modemswitcher@1.0-service.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/sony/tama-common/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/sony/tama-common/proprietary/vendor/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/scve/facereco/gModel.dat:$(TARGET_COPY_OUT_VENDOR)/etc/scve/facereco/gModel.dat \
    vendor/sony/tama-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/sony/tama-common/proprietary/vendor/etc/seccomp_policy/wfdhdcphalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdhdcphalservice.policy \
    vendor/sony/tama-common/proprietary/vendor/etc/seccomp_policy/wfdvndservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdvndservice.policy \
    vendor/sony/tama-common/proprietary/vendor/etc/seccomp_policy/wifidisplayhalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wifidisplayhalservice.policy \
    vendor/sony/tama-common/proprietary/vendor/etc/security/idd_config.pem:$(TARGET_COPY_OUT_VENDOR)/etc/security/idd_config.pem \
    vendor/sony/tama-common/proprietary/vendor/etc/security/idd_report.pem:$(TARGET_COPY_OUT_VENDOR)/etc/security/idd_report.pem \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/bmp380_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/bmp380_0.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/lsm6dsm_0_8g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lsm6dsm_0_8g.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sdm845_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_ak991x_0.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sdm845_bmp380_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_bmp380_0.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sdm845_lsm6dsm_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_lsm6dsm_0.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sdm845_tmd2725.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_tmd2725.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_disabled.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_enabled.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_aont.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_basic_gestures.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_bring_to_ear.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_ccd.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_ccd_v2_walk.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_ccd_v3_walk.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_cm.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_dae.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_device_orient.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_diag_filter.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_distance_bound.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_dpc.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_facing.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_fmv.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_geomag_rv.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_gyro_cal.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_heart_rate.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_mag_cal.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_mag_cal_legacy.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_multishake.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_pedometer.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rmd.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rotv.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_smd.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_disabled.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_enabled.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_to_wake.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_wrist_pedo.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/config/tmd2725.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/tmd2725.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/sns_reg_version:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/sns_reg_version \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/somc/sdm845_lsm6dsm_0_accel_miscta.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/somc/sdm845_lsm6dsm_0_accel_miscta.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/somc/sdm845_lsm6dsm_0_gyro_miscta.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/somc/sdm845_lsm6dsm_0_gyro_miscta.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sensors/registry/somc/tmd2725_prox_miscta.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/somc/tmd2725_prox_miscta.json \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/clearphase_sp_param.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/clearphase_sp_param.bin \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/effect_params.data:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/effect_params.data \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/sforce_param_arm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/sforce_param_arm.bin \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/sforce_param_qdsp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/sforce_param_qdsp.bin \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/xloud_param_arm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/xloud_param_arm.bin \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/xloud_param_qdsp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/xloud_param_qdsp.bin \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_44k_MainCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_MainCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_44k_MainSubSemCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_MainSubSemCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_44k_MainSubSoiCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_MainSubSoiCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_44k_NoCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_NoCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_44k_SubSemCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_SubSemCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_44k_SubSoiCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_44k_SubSoiCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_48k_MainCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_MainCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_48k_MainSubSemCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_MainSubSemCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_48k_MainSubSoiCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_MainSubSoiCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_48k_NoCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_NoCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_48k_SubSemCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_SubSemCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/sony_effect/znr_param_48k_SubSoiCam.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/sony_effect/znr_param_48k_SubSoiCam.tbl \
    vendor/sony/tama-common/proprietary/vendor/etc/wfdconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wfdconfig.xml \
    vendor/sony/tama-common/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/sony/tama-common/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/sony/tama-common/proprietary/vendor/firmware/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_gmu.bin \
    vendor/sony/tama-common/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/sony/tama-common/proprietary/vendor/firmware/a630_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b00 \
    vendor/sony/tama-common/proprietary/vendor/firmware/a630_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b01 \
    vendor/sony/tama-common/proprietary/vendor/firmware/a630_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b02 \
    vendor/sony/tama-common/proprietary/vendor/firmware/a630_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.mdt \
    vendor/sony/tama-common/proprietary/vendor/firmware/fpctzfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.b00 \
    vendor/sony/tama-common/proprietary/vendor/firmware/fpctzfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.b02 \
    vendor/sony/tama-common/proprietary/vendor/firmware/fpctzfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.b03 \
    vendor/sony/tama-common/proprietary/vendor/firmware/fpctzfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.b04 \
    vendor/sony/tama-common/proprietary/vendor/firmware/fpctzfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.b05 \
    vendor/sony/tama-common/proprietary/vendor/firmware/fpctzfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.b06 \
    vendor/sony/tama-common/proprietary/vendor/firmware/fpctzfingerprint.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.b07 \
    vendor/sony/tama-common/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/sony/tama-common/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/sony/tama-common/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/sony/tama-common/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/sony/tama-common/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/sony/tama-common/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b00 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b01 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b02 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b03 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b04 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b05 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b06 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b07 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzhdcp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.mdt \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b00 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b01 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b02 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b03 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b04 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b05 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b06 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b07 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwidevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.mdt \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b00 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b01 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b02 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b03 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b04 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b05 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b06 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b07 \
    vendor/sony/tama-common/proprietary/vendor/firmware/tzwvcpybuf.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.mdt \
    vendor/sony/tama-common/proprietary/vendor/lib/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.default.bin \
    vendor/sony/tama-common/proprietary/vendor/lib/camera/systemdefault.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/systemdefault.bin \
    vendor/sony/tama-common/proprietary/vendor/lib/camera/titan17x_usecases.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/titan17x_usecases.bin \
    vendor/sony/tama-common/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/sony/tama-common/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/sony/tama-common/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/sony/tama-common/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/sony/tama-common/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/sony/tama-common/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/sony/tama-common/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    libFileMux \
    vendor.somc.hardware.swiqi@1.0 \
    libOmxMux \
    android.hardware.sensors@2.0-impl \
    btaudio_offload_if \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.imscmservice@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0_vendor \
    com.qualcomm.qti.imscmservice@2.1_vendor \
    com.qualcomm.qti.imscmservice@2.2_vendor \
    com.qualcomm.qti.uceservice@2.0_vendor \
    com.qualcomm.qti.uceservice@2.1_vendor \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.gnss@2.0-impl-qti \
    audio.primary.sdm845 \
    com.qualcomm.qti.ant@1.0-impl \
    sound_trigger.primary.sdm845 \
    thermal.somc \
    vendor.qti.esepowermanager@1.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.0-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    vulkan.sdm845 \
    touch_cover \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsxml \
    lib-siputility \
    lib-uceservice \
    libC2D2 \
    libCB \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libOpenCL \
    libQSEEComAPI \
    libQTEEConnector_vendor \
    libRSDriver_adreno \
    libSecureUILib \
    libStDrvInt \
    liba2dpoffload \
    libacdb-fts \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libaoa \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioparsers \
    libbatching \
    libbatterylistener \
    libbccQTI \
    libbluetooth_audio_session_qti \
    libc2d30_bltlib \
    libcacao_common \
    libcacertclient \
    libcamera_nn_stub \
    libcameralight \
    libcamxfdalgov7 \
    libcamxfdalgov8 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnn \
    libcapiv2vop \
    libcdsp_default_listener \
    libcdsprpc \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libcomprcapture \
    libconfigdb \
    libcsd-client \
    libdevice_security_vendor \
    libdiag \
    libdisp-aba \
    libdisplayqos \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libexthwplugin \
    libfastcvdsp_stub \
    libfastcvopt \
    libfastrpc_utf_stub \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgdtap \
    libgeofencing \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgsl \
    libhdcprx_module \
    libhdcptx_module \
    libhdmiedid \
    libhdmipassthru \
    libhdr_tm \
    libhfp \
    libidd \
    libidl \
    libizat_client_api \
    libizat_core \
    libjnihelper \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    liblights-core \
    liblistenjni \
    liblistensoundmodel2 \
    libllvm-glnext \
    libllvm-qcom \
    libloc_core \
    liblocation_api \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libmdmdetect \
    libmdsprpc \
    libminksocket \
    libmiscta \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmosal_proprietary \
    libmmparser_lite_proprietary \
    libmulawdec \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    liboemcrypto \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libpfter \
    libqcci_legacy \
    libqcmaputils \
    libqcrilFramework \
    libqdi \
    libqdp \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqrtr \
    libqseed3 \
    libqsocket \
    libqtigef \
    libqtikeymaster4 \
    librcc \
    librebuffering \
    libril-qc-hal-qmi \
    libril-qc-ltedirectdisc \
    libril-qc-qmi-1 \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librpmb \
    librs_adreno \
    librs_adreno_sha1 \
    libscveBlobDescriptor \
    libscveBlobDescriptor_stub \
    libscveCommon \
    libscveCommon_stub \
    libscveFaceRecognition \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libscvePanorama \
    libscvePanorama_lite \
    libscveScan3D \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsecureui \
    libsecureui_svcsock \
    libsensorcal \
    libsensorslog \
    libsettings \
    libsndmonitor \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsnsapi \
    libsnsdiaglog \
    libsomc_thermal \
    libsonydseehxwrapper \
    libspcom \
    libspkrprot \
    libspl \
    libssc \
    libssc_default_listener \
    libssd \
    libstagefright_hdcp \
    libsuntory \
    libswiqisettinghelper \
    libsys-utils \
    libsysmon_cdsp_skel \
    libsystem_health_mon \
    libta \
    libthermal_engine \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libtzdrmgenprov \
    libvppclient \
    libvpphcp \
    libvpphvx \
    libvpplibrary \
    libwfdhdcpcp \
    libwms \
    libwqe \
    libwvhidl \
    libwvtee \
    libxml \
    libxtadapter \
    libwvdrmengine \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    libasphere \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0-service \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0_vendor \
    vendor.qti.hardware.radio.ims@1.1_vendor \
    vendor.qti.hardware.radio.ims@1.2_vendor \
    vendor.qti.hardware.radio.ims@1.3_vendor \
    vendor.qti.hardware.radio.ims@1.4_vendor \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.ims.callinfo@1.0_vendor \
    vendor.qti.ims.rcsconfig@1.0_vendor \
    vendor.qti.imsrtpservice@2.0_vendor \
    vendor.qti.imsrtpservice@2.1-service-Impl \
    vendor.qti.imsrtpservice@2.1_vendor \
    vendor.qti.latency@2.0 \
    vendor.semc.hardware.light@1.0 \
    vendor.semc.system.idd@1.0 \
    vendor.somc.hardware.radio@1.0 \
    vendor.somc.hardware.security.secd@1.0 \
    vendor.somc.hardware.swiqi@1.0-impl \
    vendor.somc.hardware.swiqi@1.0_vendor \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.haf \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libexcal_ckb_service_plugin \
    libexcal_color_ctrl_plugin \
    libexcal_debug_display_plugin \
    libexcal_exposure_ctrl_plugin \
    libexcal_flicker_detector_plugin \
    libexcal_focus_stats_conv_plugin \
    libexcal_food_comp_plugin \
    libexcal_food_detector_plugin \
    libexcal_fusion_comp_plugin \
    libexcal_hdr_plugin \
    libexcal_idt_ctrl_plugin \
    libexcal_iq_ctrl_plugin \
    libexcal_motion_detector_plugin \
    libexcal_motion_estimation_plugin \
    libexcal_multiframe_nr_plugin \
    libexcal_object_detector_plugin \
    libexcal_object_tracker_plugin \
    libexcal_prc_image_conv_plugin \
    libexcal_process_ctrl_plugin \
    libexcal_raw_dump_plugin \
    libexcal_req_ctrl_plugin \
    libexcal_scene_detector_plugin \
    libexcal_snapshot_ctrl_plugin \
    libexcal_splitter_plugin \
    libexcal_stream_ctrl_plugin \
    camera.qcom \
    libFileMux_proprietary \
    libOmxMux_proprietary \
    libOmxVideoDSMode \
    libOmxVpp \
    libSNPE \
    libadm \
    libadpcmdec \
    libc++_shared \
    libcom.qti.chinodeutils \
    libcppf \
    libfastcrc \
    libmmosal_vendor \
    libmmrtpdecoder_proprietary \
    libmmrtpencoder_proprietary \
    libpn553_fw \
    libscveFaceLandmarks \
    libsmwrapper \
    libsomc_alfortlp \
    libsomc_alfortlpserv \
    libsomc_bordeaux \
    libsomc_bordeauxrsc \
    libsomc_buttercake \
    libsomc_buttercakersc \
    libsomc_camerahal \
    libsomc_canele \
    libsomc_canelersc \
    libsomc_cheesescone \
    libsomc_cheesesconersc \
    libsomc_chokoballcmn \
    libsomc_financier \
    libsomc_financierrsc \
    libsomc_madeleine_core \
    libsomc_marble \
    libsomc_marblersc \
    libsomc_melonpan \
    libsomc_melonpanrsc \
    libsomc_mln \
    libsomc_mugichoco \
    libsomc_mugichocorsc \
    libsomc_pretzchoco \
    libsomc_pretzchocorsc \
    libsomc_raisin \
    libsomc_raisincl \
    libsomc_raisinclrsc \
    libsomc_raisinrsc \
    libsomc_shortcake \
    libsomc_shortcakersc \
    libsomc_spica \
    libsomc_spicarsc \
    libsomc_sumomo \
    libsomc_sumomorsc \
    libsomc_toppo \
    libsomc_topporsc \
    libsomc_yummy \
    libsomc_yummyrsc \
    libsony_fooddetect \
    libsony_naruto \
    libsymphony-cpu \
    libsymphonypower \
    libwfdcodecv4l2_proprietary \
    libwfdcommonutils_proprietary \
    libwfdconfigutils_proprietary \
    libwfddisplayconfig_proprietary \
    libwfdhdcpservice_proprietary \
    libwfdmminterface_proprietary \
    libwfdmmservice_proprietary \
    libwfdmmsrc_proprietary \
    libwfdmodulehdcpsession \
    libwfdrtsp_proprietary \
    libwfdsessionmodule \
    libwfdsourcesession_proprietary \
    libwfdsourcesm_proprietary \
    libwfduibcinterface_proprietary \
    libwfduibcsink_proprietary \
    libwfduibcsinkinterface_proprietary \
    libwfduibcsrc_proprietary \
    libwfduibcsrcinterface_proprietary \
    libwfdutils_proprietary \
    libznr \
    local_libcamera_metadata \
    libsonypostprocbundle \
    libsonysweffect \
    libznrwrapper \
    vendor.qti.hardware.wifidisplaysession@1.0_vendor \
    vendor.qti.hardware.wifidisplaysessionl@1.0-halimpl \
    vendor.somc.camera.device@3.2-impl \
    vendor.somc.camera.device@3.3-impl \
    vendor.somc.camera.device@3.4-impl \
    vendor.somc.hardware.camera.cacao@1.0 \
    vendor.somc.hardware.camera.cacao@2.0 \
    vendor.somc.hardware.camera.cacao@3.0 \
    vendor.somc.hardware.camera.cacao@3.1-impl \
    vendor.somc.hardware.camera.cacao@3.1 \
    vendor.somc.hardware.camera.device@1.0 \
    vendor.somc.hardware.camera.provider@1.0 \
    com.fingerprints.extension@1.0 \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    vendor.qti.hardware.alarm@1.0-impl \
    lib-imsvtcore \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    libMiscTaWrapper \
    libcpion \
    libdpmqmihal \
    libhdcpsrm \
    libhexagon_nn_stub \
    libnlnetmgr \
    libprotobuf-c-idd \
    libqdma_file_agent \
    libtpm \
    unnhal-acc-adreno \
    unnhal-acc-common \
    unnhal-acc-hvx \
    vendor.qti.hardware.alarm@1.0 \
    vendor.semc.hardware.thermal@1.0 \
    vendor.somc.hardware.miscta@1.0 \
    vendor.somc.hardware.modemswitcher@1.0 \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    libFastRPC_UTF_Forward_skel \
    libVC1Dec \
    libVC1DecDsp_skel \
    libapps_mem_heap \
    libcamera_nn_skel \
    libcvpdsp_skel \
    libdspCV_skel \
    libdsp_streamer_add_constant \
    libdsp_streamer_skel \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhexagon_nn_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsnpe_dsp_v65_skel \
    libsns_device_mode_skel \
    libsns_low_lat_stream_skel \
    libsomc_alfortlpserv_skel \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libimscamera_jni \
    libimsmedia_jni \
    libmmosal \
    libmmparser_lite \
    libmmrtpdecoder \
    libmmrtpencoder \
    libwfdclient \
    libwfdcommonutils \
    libwfdconfigutils \
    libwfddisplayconfig \
    libwfdmminterface \
    libwfdmmsink \
    libwfdrtsp \
    libwfdsinksm \
    libwfduibcinterface \
    libwfduibcsink \
    libwfduibcsinkinterface \
    libwfduibcsrc \
    libwfduibcsrcinterface \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.imsrtpservice@2.0 \
    vendor.qti.imsrtpservice@2.1 \
    libwfdavenhancements \
    libwfdmmsrc_system \
    libwfdservice \
    vendor.qti.hardware.wifidisplaysession@1.0 \
    vendor.qti.hardware.wifidisplaysession_aidl-V1-ndk \
    com.qualcomm.qti.dpm.api@1.0 \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libwfdnative \
    CneApp \
    IWlanService \
    TimeService \
    HotwordEnrollmentOKGoogleWCD9340 \
    HotwordEnrollmentXGoogleWCD9340 \
    PowerOffAlarm \
    QtiTelephonyService \
    uceShimService \
    WfdService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    WfdCommon \
    audiosphere \
    QtiTelephonyServicelibrary \
    com.android.hotwordenrollment.common.util \
    com.qti.dpmframework \
    com.qualcomm.qti.imscmservice-V2.0-java \
    com.qualcomm.qti.imscmservice-V2.1-java \
    com.qualcomm.qti.imscmservice-V2.2-java \
    dpmapi \
    qcrilhook \
    qti-telephony-common \
    android.hardware.gnss@2.0-service-qti.xml \
    vendor.qti.gnss@3.0-service.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    cdsprpcd \
    cnd \
    cnss-daemon \
    cnss_diag \
    dpmQmiMgr \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.1-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gnss@2.0-service-qti \
    android.hardware.neuralnetworks@1.2-service-qti \
    android.hardware.sensors@2.0-service \
    fpc_fingerprint@2.1_HIDL-service \
    kobjeventd \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.esepowermanager@1.0-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.semc.system.idd@1.0-service \
    vendor.somc.hardware.camera.provider@1.0-service \
    vendor.somc.hardware.miscta@1.0-service \
    vendor.somc.hardware.modemswitcher@1.0-service \
    iddd \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    ipacm-diag \
    irsc_util \
    keyprovd \
    loc_launcher \
    lowi-server \
    mlid \
    mlog_qmi_service \
    mm-pp-dpps \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    ppd \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sct_service \
    seemp_healthd \
    sensors.qti \
    sony-modem-switcher \
    sscrpcd \
    ta_qmi_service \
    tad \
    taimport_vendor \
    tftp_server \
    thermal-engine \
    time_daemon \
    vppservice \
    wfdhdcphalservice \
    wifidisplayhalservice \
    wvkbd \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent \
    dpmd \
    wfdservice

PRODUCT_PACKAGES += \
    system_ext_priv-app_WfdService_lib_arm64_libwfdnative_so
